<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Account.aspx.cs" Inherits="Wallet.Account" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Button ID="btmLogout" runat="server" Text="Logout" OnClick="btnLogout_Click" style="width: 57px" />
            <br /><br />
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LoginDBConnectionString %>" SelectCommand="SELECT FirstName, LastName, PhoneNumber, Username FROM [UserAccount] A, [Login] L Where L.Username = @UserName" UpdateCommand="">
                <SelectParameters>
                    <asp:SessionParameter Name="UserName" SessionField="UserName" Type="String" />
                </SelectParameters>
            </asp:SqlDataSource>
        </div>
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="UserName" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:CommandField ShowEditButton="True" />
                    <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                    <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                    <asp:BoundField DataField="PhoneNumber" HeaderText="MobileNumber" SortExpression="MobileNumber" />
                    <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="True" SortExpression="UserName" />
                </Columns>
            </asp:GridView>
        </div>
        <br /><br /><br /><br />
        <table style="border:5px solid white">
            <tr>
                <td><asp:Label ID="bankIDLabel" runat="server" Text="BankID"></asp:Label></td>
                <td><asp:TextBox ID="BankID" runat="server"></asp:TextBox></td>
                <td><asp:Label ID="accountNumLabel" runat="server" Text="AccountNumber"></asp:Label></td>
                <td><asp:TextBox ID="accountNumber" runat="server"></asp:TextBox></td>
                <td><asp:Label ID="isPrimaryLabel" runat="server" Text="isPrimary"></asp:Label></td>
                <td><asp:TextBox ID="isPrimary" runat="server"></asp:TextBox></td>
                <td><asp:Button ID="addAccountButton" runat="server" Text="AddBankAccount" OnClick="onClickAddAccount" /></td>
            </tr>
        </table>
        <div>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" DeleteCommand="DELETE FROM BankAccount WHERE [BankID]=@bankID and [AccountNumber]=@accountNumber and [SSN]=@ssn" ConnectionString="<%$ ConnectionStrings:LoginDBConnectionString %>" SelectCommand="SELECT [SSN], [BankID], [AccountNumber], [isPrimary] FROM [BankAccount] WHERE ([SSN] = @ssn)" UpdateCommand="Update BankAccount set [BankID]=@bankID, [AccountNumber]=@accountNumber, [isPrimary]=@IsPrimary where ([SSN] = @ssn)">
                <SelectParameters>
                    <asp:SessionParameter Name="ssn" SessionField="ssn" Type="String" />
                </SelectParameters>
            </asp:SqlDataSource>
        </div>
        <div>
            <asp:GridView ID="GridView2" runat="server"  AutoGenerateColumns="False"  DataKeyNames="bankID,accountNumber,ssn" DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True">
                <Columns>
                    <asp:CommandField ShowEditButton="True" />
                    <asp:BoundField DataField="bankID" HeaderText="bankID" ReadOnly="True" SortExpression="bankID" />
                    <asp:BoundField DataField="accountNumber" HeaderText="accountNumber" ReadOnly="True" SortExpression="accountNumber" />
                    <asp:BoundField DataField="IsPrimary" HeaderText="IsPrimary" SortExpression="IsPrimary" />
                </Columns>
            </asp:GridView>
       </div>
    </form>
</body>
</html>
